-- manifest_generated.lua
-- GENERATED by ADDONCONTEXT/Scripts/avatars/generate.js. Do not edit by hand.
local addonName, addon = ...

addon.AvatarManifest = {
  version = 1,
  resolutions = { 96 },
  pathPrefix = "Interface\\AddOns\\Scoot\\media\\avatars\\",
  slots = { "helmetBack", "ears", "head", "tusks", "teeth", "eyes", "facialHair", "hair", "jewelry", "helmetFront" },
  slotLayer = {
    helmetBack = {
      layer = "ARTWORK",
      sub = -5,
    },
    ears = {
      layer = "ARTWORK",
      sub = -3,
    },
    head = {
      layer = "ARTWORK",
      sub = 0,
    },
    tusks = {
      layer = "ARTWORK",
      sub = 1,
    },
    teeth = {
      layer = "ARTWORK",
      sub = 1,
    },
    eyes = {
      layer = "ARTWORK",
      sub = 2,
    },
    facialHair = {
      layer = "ARTWORK",
      sub = 3,
    },
    hair = {
      layer = "ARTWORK",
      sub = 4,
    },
    jewelry = {
      layer = "ARTWORK",
      sub = 5,
    },
    helmetFront = {
      layer = "ARTWORK",
      sub = 6,
    },
  },
  palettes = {
    skin = {
      { 0.996, 0.906, 0.839 },
      { 0.95, 0.82, 0.72 },
      { 0.9, 0.74, 0.6 },
      { 0.72, 0.54, 0.42 },
      { 0.52, 0.37, 0.28 },
      { 0.4, 0.58, 0.32 },
      { 0.3, 0.5, 0.36 },
      { 0.62, 0.55, 0.78 },
      { 0.96, 0.94, 0.91 },
    },
    hair = {
      { 0.09, 0.07, 0.06 },
      { 0.28, 0.18, 0.1 },
      { 0.52, 0.35, 0.18 },
      { 0.8, 0.64, 0.34 },
      { 0.7, 0.14, 0.12 },
      { 0.86, 0.86, 0.9 },
      { 0.2, 0.58, 0.58 },
      { 0.58, 0.46, 0.78 },
    },
    metal = {
      { 0.66, 0.69, 0.74 },
      { 0.83, 0.85, 0.89 },
      { 0.8, 0.65, 0.3 },
      { 0.46, 0.48, 0.53 },
      { 0.3, 0.32, 0.38 },
      { 0.55, 0.4, 0.26 },
    },
    eyes = {
      { 0.55, 0.4, 0.2 },
      { 0.3, 0.55, 0.85 },
      { 0.35, 0.7, 0.4 },
      { 0.9, 0.8, 0.3 },
      { 0.45, 1, 0.55 },
      { 0.2, 0.85, 1 },
      { 0.95, 0.55, 0.1 },
      { 0.85, 0.25, 1 },
    },
  },
  classTint = {},
  races = {
    Human = {
      defaultsBySex = {
        Male = {
          head = "m",
          ears = "base",
          eyes = "brown",
          hair = "short",
          facialHair = "none",
          jewelry = "none",
          helmetBack = "none",
          helmetFront = "none",
        },
        Female = {
          head = "f",
          ears = "base",
          eyes = "brown",
          hair = "long",
          facialHair = "none",
          jewelry = "none",
          helmetBack = "none",
          helmetFront = "none",
        },
      },
      variants = {
        helmetBack = {
          {
            key = "none",
            label = "None",
          },
          {
            key = "plate",
            label = "Plate",
            tintable = true,
            ramp = "metal",
            defaultColor = { 0.66, 0.69, 0.74 },
          },
        },
        ears = {
          {
            key = "base",
            label = "Ears",
            tintable = true,
            ramp = "skin",
            defaultColor = { 0.996, 0.906, 0.839 },
          },
        },
        head = {
          {
            key = "m",
            label = "Masculine",
            tintable = true,
            ramp = "skin",
            defaultColor = { 0.996, 0.906, 0.839 },
          },
          {
            key = "f",
            label = "Feminine",
            tintable = true,
            ramp = "skin",
            defaultColor = { 0.996, 0.906, 0.839 },
          },
        },
        tusks = {
          {
            key = "none",
            label = "None",
          },
        },
        teeth = {
          {
            key = "none",
            label = "None",
          },
        },
        eyes = {
          {
            key = "brown",
            label = "Brown",
          },
          {
            key = "blue",
            label = "Blue",
          },
          {
            key = "green",
            label = "Green",
          },
          {
            key = "amber",
            label = "Amber",
          },
        },
        facialHair = {
          {
            key = "none",
            label = "None",
          },
          {
            key = "stubble",
            label = "Stubble",
            tintable = true,
            ramp = "hair",
            defaultColor = { 0.52, 0.35, 0.18 },
          },
          {
            key = "beard",
            label = "Beard",
            tintable = true,
            ramp = "hair",
            defaultColor = { 0.52, 0.35, 0.18 },
          },
          {
            key = "mustache",
            label = "Mustache",
            tintable = true,
            ramp = "hair",
            defaultColor = { 0.52, 0.35, 0.18 },
          },
        },
        hair = {
          {
            key = "none",
            label = "None",
          },
          {
            key = "short",
            label = "Short",
            tintable = true,
            ramp = "hair",
            defaultColor = { 0.52, 0.35, 0.18 },
          },
          {
            key = "long",
            label = "Long",
            tintable = true,
            ramp = "hair",
            defaultColor = { 0.52, 0.35, 0.18 },
          },
          {
            key = "topknot",
            label = "Topknot",
            tintable = true,
            ramp = "hair",
            defaultColor = { 0.52, 0.35, 0.18 },
          },
          {
            key = "ponytail",
            label = "Ponytail",
            tintable = true,
            ramp = "hair",
            defaultColor = { 0.52, 0.35, 0.18 },
          },
        },
        jewelry = {
          {
            key = "none",
            label = "None",
          },
          {
            key = "earring",
            label = "Earring",
          },
          {
            key = "nosering",
            label = "Nose ring",
          },
        },
        helmetFront = {
          {
            key = "none",
            label = "None",
          },
          {
            key = "plate",
            label = "Plate",
            tintable = true,
            ramp = "metal",
            defaultColor = { 0.66, 0.69, 0.74 },
          },
          {
            key = "hood",
            label = "Hood",
            tintable = true,
            ramp = "metal",
            defaultColor = { 0.55, 0.4, 0.26 },
          },
          {
            key = "horned",
            label = "Horned",
            tintable = true,
            ramp = "metal",
            defaultColor = { 0.46, 0.48, 0.53 },
          },
        },
      },
      helmets = {
        {
          key = "none",
          back = "none",
          front = "none",
        },
        {
          key = "plate",
          back = "plate",
          front = "plate",
          label = "Plate",
          tintable = true,
          ramp = "metal",
          defaultColor = { 0.66, 0.69, 0.74 },
        },
        {
          key = "hood",
          back = "none",
          front = "hood",
          label = "Hood",
          tintable = true,
          ramp = "metal",
          defaultColor = { 0.55, 0.4, 0.26 },
        },
        {
          key = "horned",
          back = "plate",
          front = "horned",
          label = "Horned",
          tintable = true,
          ramp = "metal",
          defaultColor = { 0.46, 0.48, 0.53 },
        },
      },
    },
    Orc = {
      defaultsBySex = {
        Male = {
          head = "m",
          ears = "base",
          eyes = "brown",
          hair = "topknot",
          facialHair = "none",
          tusks = "base",
          jewelry = "none",
          helmetBack = "none",
          helmetFront = "none",
        },
        Female = {
          head = "f",
          ears = "base",
          eyes = "brown",
          hair = "ponytail",
          facialHair = "none",
          tusks = "base",
          jewelry = "none",
          helmetBack = "none",
          helmetFront = "none",
        },
      },
      variants = {
        helmetBack = {
          {
            key = "none",
            label = "None",
          },
          {
            key = "plate",
            label = "Plate",
            tintable = true,
            ramp = "metal",
            defaultColor = { 0.66, 0.69, 0.74 },
          },
        },
        ears = {
          {
            key = "base",
            label = "Ears",
            tintable = true,
            ramp = "skin",
            defaultColor = { 0.4, 0.58, 0.32 },
          },
        },
        head = {
          {
            key = "m",
            label = "Masculine",
            tintable = true,
            ramp = "skin",
            defaultColor = { 0.4, 0.58, 0.32 },
          },
          {
            key = "f",
            label = "Feminine",
            tintable = true,
            ramp = "skin",
            defaultColor = { 0.4, 0.58, 0.32 },
          },
        },
        tusks = {
          {
            key = "none",
            label = "None",
          },
          {
            key = "base",
            label = "Tusks",
          },
        },
        teeth = {
          {
            key = "none",
            label = "None",
          },
        },
        eyes = {
          {
            key = "brown",
            label = "Brown",
          },
          {
            key = "blue",
            label = "Blue",
          },
          {
            key = "green",
            label = "Green",
          },
          {
            key = "amber",
            label = "Amber",
          },
        },
        facialHair = {
          {
            key = "none",
            label = "None",
          },
          {
            key = "stubble",
            label = "Stubble",
            tintable = true,
            ramp = "hair",
            defaultColor = { 0.09, 0.07, 0.06 },
          },
          {
            key = "beard",
            label = "Beard",
            tintable = true,
            ramp = "hair",
            defaultColor = { 0.09, 0.07, 0.06 },
          },
          {
            key = "mustache",
            label = "Mustache",
            tintable = true,
            ramp = "hair",
            defaultColor = { 0.09, 0.07, 0.06 },
          },
        },
        hair = {
          {
            key = "none",
            label = "None",
          },
          {
            key = "short",
            label = "Short",
            tintable = true,
            ramp = "hair",
            defaultColor = { 0.09, 0.07, 0.06 },
          },
          {
            key = "long",
            label = "Long",
            tintable = true,
            ramp = "hair",
            defaultColor = { 0.09, 0.07, 0.06 },
          },
          {
            key = "topknot",
            label = "Topknot",
            tintable = true,
            ramp = "hair",
            defaultColor = { 0.09, 0.07, 0.06 },
          },
          {
            key = "ponytail",
            label = "Ponytail",
            tintable = true,
            ramp = "hair",
            defaultColor = { 0.09, 0.07, 0.06 },
          },
        },
        jewelry = {
          {
            key = "none",
            label = "None",
          },
          {
            key = "earring",
            label = "Earring",
          },
          {
            key = "nosering",
            label = "Nose ring",
          },
        },
        helmetFront = {
          {
            key = "none",
            label = "None",
          },
          {
            key = "plate",
            label = "Plate",
            tintable = true,
            ramp = "metal",
            defaultColor = { 0.66, 0.69, 0.74 },
          },
          {
            key = "hood",
            label = "Hood",
            tintable = true,
            ramp = "metal",
            defaultColor = { 0.55, 0.4, 0.26 },
          },
          {
            key = "horned",
            label = "Horned",
            tintable = true,
            ramp = "metal",
            defaultColor = { 0.46, 0.48, 0.53 },
          },
        },
      },
      helmets = {
        {
          key = "none",
          back = "none",
          front = "none",
        },
        {
          key = "plate",
          back = "plate",
          front = "plate",
          label = "Plate",
          tintable = true,
          ramp = "metal",
          defaultColor = { 0.66, 0.69, 0.74 },
        },
        {
          key = "hood",
          back = "none",
          front = "hood",
          label = "Hood",
          tintable = true,
          ramp = "metal",
          defaultColor = { 0.55, 0.4, 0.26 },
        },
        {
          key = "horned",
          back = "plate",
          front = "horned",
          label = "Horned",
          tintable = true,
          ramp = "metal",
          defaultColor = { 0.46, 0.48, 0.53 },
        },
      },
    },
    NightElf = {
      defaultsBySex = {
        Male = {
          head = "m",
          ears = "base",
          eyes = "amber",
          hair = "long",
          facialHair = "none",
          jewelry = "none",
          helmetBack = "none",
          helmetFront = "none",
        },
        Female = {
          head = "f",
          ears = "base",
          eyes = "amber",
          hair = "long",
          facialHair = "none",
          jewelry = "none",
          helmetBack = "none",
          helmetFront = "none",
        },
      },
      variants = {
        helmetBack = {
          {
            key = "none",
            label = "None",
          },
          {
            key = "plate",
            label = "Plate",
            tintable = true,
            ramp = "metal",
            defaultColor = { 0.66, 0.69, 0.74 },
          },
        },
        ears = {
          {
            key = "base",
            label = "Ears",
            tintable = true,
            ramp = "skin",
            defaultColor = { 0.62, 0.55, 0.78 },
          },
        },
        head = {
          {
            key = "m",
            label = "Masculine",
            tintable = true,
            ramp = "skin",
            defaultColor = { 0.62, 0.55, 0.78 },
          },
          {
            key = "f",
            label = "Feminine",
            tintable = true,
            ramp = "skin",
            defaultColor = { 0.62, 0.55, 0.78 },
          },
        },
        tusks = {
          {
            key = "none",
            label = "None",
          },
        },
        teeth = {
          {
            key = "none",
            label = "None",
          },
        },
        eyes = {
          {
            key = "brown",
            label = "Brown",
          },
          {
            key = "blue",
            label = "Blue",
          },
          {
            key = "green",
            label = "Green",
          },
          {
            key = "amber",
            label = "Amber",
          },
        },
        facialHair = {
          {
            key = "none",
            label = "None",
          },
          {
            key = "stubble",
            label = "Stubble",
            tintable = true,
            ramp = "hair",
            defaultColor = { 0.2, 0.58, 0.58 },
          },
          {
            key = "beard",
            label = "Beard",
            tintable = true,
            ramp = "hair",
            defaultColor = { 0.2, 0.58, 0.58 },
          },
          {
            key = "mustache",
            label = "Mustache",
            tintable = true,
            ramp = "hair",
            defaultColor = { 0.2, 0.58, 0.58 },
          },
        },
        hair = {
          {
            key = "none",
            label = "None",
          },
          {
            key = "short",
            label = "Short",
            tintable = true,
            ramp = "hair",
            defaultColor = { 0.2, 0.58, 0.58 },
          },
          {
            key = "long",
            label = "Long",
            tintable = true,
            ramp = "hair",
            defaultColor = { 0.2, 0.58, 0.58 },
          },
          {
            key = "topknot",
            label = "Topknot",
            tintable = true,
            ramp = "hair",
            defaultColor = { 0.2, 0.58, 0.58 },
          },
          {
            key = "ponytail",
            label = "Ponytail",
            tintable = true,
            ramp = "hair",
            defaultColor = { 0.2, 0.58, 0.58 },
          },
        },
        jewelry = {
          {
            key = "none",
            label = "None",
          },
          {
            key = "earring",
            label = "Earring",
          },
          {
            key = "nosering",
            label = "Nose ring",
          },
        },
        helmetFront = {
          {
            key = "none",
            label = "None",
          },
          {
            key = "plate",
            label = "Plate",
            tintable = true,
            ramp = "metal",
            defaultColor = { 0.66, 0.69, 0.74 },
          },
          {
            key = "hood",
            label = "Hood",
            tintable = true,
            ramp = "metal",
            defaultColor = { 0.55, 0.4, 0.26 },
          },
          {
            key = "horned",
            label = "Horned",
            tintable = true,
            ramp = "metal",
            defaultColor = { 0.46, 0.48, 0.53 },
          },
        },
      },
      helmets = {
        {
          key = "none",
          back = "none",
          front = "none",
        },
        {
          key = "plate",
          back = "plate",
          front = "plate",
          label = "Plate",
          tintable = true,
          ramp = "metal",
          defaultColor = { 0.66, 0.69, 0.74 },
        },
        {
          key = "hood",
          back = "none",
          front = "hood",
          label = "Hood",
          tintable = true,
          ramp = "metal",
          defaultColor = { 0.55, 0.4, 0.26 },
        },
        {
          key = "horned",
          back = "plate",
          front = "horned",
          label = "Horned",
          tintable = true,
          ramp = "metal",
          defaultColor = { 0.46, 0.48, 0.53 },
        },
      },
    },
  },
}
